### ISSUE TITLE
Issue on v 1.6.0 

### ISSUE THREAD

**Issue by drdr34m** [BitMaker-hub/NerdMiner_v2#115]
Hello I just update my nerd miners to 1.6.0 and I can't edit my BTC address cause I see only wifi setup and nothing more. When I try to connect to my WiFi the miner restarts and can't save my credentials. I try reset to factory bin and than again flush 1.6.0 with same result. Any one have same or similar issue?
Even with older version same issue. Is there a way to complete erase flash?
Thank you and keep up the great job

**Comment by BitMaker-hub** [comment]
There is also a way to erase complete flash using the following tool [https://espressif.github.io/esptool-js/](https://espressif.github.io/esptool-js/)

I'll try to add Dyflasher the way to edit this settings before flashing them too.
