### ISSUE TITLE
Re-start every 2 minutes

### ISSUE THREAD

**Issue by andrea8980** [BitMaker-hub/NerdMiner_v2#118]
Everything seems fine, my NerdMiner works even the hashrate  and all the stats are 0 (could be the pool, could be the router, I thinnk i'm going to solve it later). But the real issue is that every 2' restart from the connection page.

**Comment by Mrbengein** [comment]
Hello,

I have the same issue

**Comment by andrea8980** [comment]
I solved installig the 1.5 release. That works. The problem with the hash rate was due to the address, that was taproot. Now everything works, even if sometimes it stops and I need to unplug it and replug again
