### ISSUE TITLE
Feature request: Remember display on reset

### ISSUE THREAD

**Issue by FinalTwist** [BitMaker-hub/NerdMiner_v2#128]
My nerdminer appearntly overheats every 5 hours or so, and i love one of the displays (i want to use this as a clock).  however as it constantly resets this makes it impossible to use in that manner as it resets to the default screen every few hours.

Any way to choose which display mode the nerdminer resets to?  Or perhaps have it remember which display was last showing when it resets?

**Comment by BitMaker-hub** [comment]
This is frequently asked. We will include on next release
