### ISSUE TITLE
Rare overheat & restart

### ISSUE THREAD

**Issue by sk3pt1k** [BitMaker-hub/NerdMiner_v2#141]
Wanted to know if anyone else has noticed this issue. My miner typically mines around 40 degrees, but now and then I look and it has suddenly increased to 50+ degrees and restarts shortly thereafter. Is it getting stuck in a short loop? Is this temperature read genuine? Hard to track down consistently.

**Comment by BitMaker-hub** [comment]
There is still something to do with temperature compensation, ESP32 is not providing a very good value
