### ISSUE TITLE
online flash tool not working for the esp32 wroom-32 devkit 1

### ISSUE THREAD

**Issue by roblatour** [BitMaker-hub/NerdMiner_v2#144]
The flash tool at https://bitmaker-hub.github.io/diyflasher/ is not working for the esp32 wroom-32 devkit 1.

I tried both Chrome and Brave.

I pressed and held the boot button, pressed the EN button, and released the boot button (to put the device in upload mode).

With Chrome you can select the board and the port, but then in about 2 seconds the webpage says the firmware was flashed but it appears it was not as the Nerdminer Accesss Point doesn't appear in the list of wifi networks I can connect too.

Also, the percent completion bars remain unchanged (all white).

With Brave you can select the board but not the port.  After selecting the board and clicking flash nothing happens.

I also tried to flash the board using the esspressif flash tool with the binaries on github - but that didn't work either.

When I turn on a com port monitor, I get the following:

19:10:20.033 -> 
19:10:20.033 -> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
19:10:20.080 -> invalid header: 0xffffffff
19:10:20.112 -> invalid header: 0xffffffff
19:10:20.158 -> invalid header: 0xffffffff
19:10:20.205 -> invalid header: 0xffffffff
19:10:20.252 -> invalid header: 0xffffffff
19:10:20.283 -> invalid header: 0xffffffff
19:10:20.315 -> invalid header: 0xffffffff
19:10:20.393 -> invalid header: 0xfffffff�ets Jul 29 2019 12:21:46
19:10:20.393 -> 
19:10:20.393 -> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
19:10:20.439 -> invalid header: 0xffffffff
19:10:20.471 -> invalid header: 0xffffffff
19:10:20.517 -> invalid header: 0xffffffff
19:10:20.563 -> invalid header: 0xffffffff
19:10:20.609 -> invalid header: 0xffffffff
19:10:20.641 -> invalid header: 0xffffffff
19:10:20.674 -> invalid header: 0xffffffff
19:10:20.752 -> invalid header: 0xfffffff�ets Jul 29 2019 12:21:46
19:10:20.752 -> 
19:10:20.752 -> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
19:10:20.800 -> invalid header: 0xffffffff
19:10:20.845 -> invalid header: 0xffffffff
19:10:20.893 -> invalid header: 0xffffffff
19:10:20.940 -> invalid header: 0xffffffff
19:10:20.985 -> invalid header: 0xffffffff
19:10:21.018 -> invalid header: 0xffffffff
19:10:21.064 -> invalid header: 0xffffffff
19:10:21.111 -> invalid header: 0xffffffffets Jul 29 2019 12:21:46
...

The tool has worked fine for my T-Display S3 boards, its just not working for my esp32 wroom-32 devkit 1 board.

**Comment by BitMaker-hub** [comment]
Hi, you have to put board on boot mode. Hold boot and then ress reset or unlug and plug cable again. This should work

**Comment by roblatour** [comment]
I agree, that should work - and I did try holding the boot button down and then the 'En' button but it didn't work.  Also tried unplugging it and plugging it in; still didn't work.

Here is what the screen looks like under chrome:
https://ibb.co/sRMcygb

Notice the progress bars are blank, when I flashed my T-Display S3 these turn a solid blue/purple, but with the esp32-WROOM they don't.

I can however flash the board with a simple hello world sketch from the Arduino IDE without any issues.

**Comment by BuckligerBaron** [comment]
I had the same Issue on Windows. After installing this Driver [https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers](url) an additional serial Interface was installed (Com7 in my Case) and using this new Interface i could flash the Firmware. Without the Driver the ESP was recognized on Com5.
![CP210](https://github.com/BitMaker-hub/NerdMiner_v2/assets/107643900/1140e26f-9c44-4342-8923-26760330c8a0)

**Comment by roblatour** [comment]
@BuckligerBaron Thank you - installing the driver resolved the issue for me.

**Comment by Tuk2525-j** [comment]
Esp32I can't upload either.

**Comment by dejota46** [comment]
> I had the same Issue on Windows. After installing this Driver [https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers](url) an additional serial Interface was installed (Com7 in my Case) and using this new Interface i could flash the Firmware. Without the Driver the ESP was recognized on Com5 by Windows. Please see Screenshot.
> 
> ![CP210](https://private-user-images.githubusercontent.com/107643900/266636848-1140e26f-9c44-4342-8923-26760330c8a0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzEyMTIsIm5iZiI6MTcwODAzMDkxMiwicGF0aCI6Ii8xMDc2NDM5MDAvMjY2NjM2ODQ4LTExNDBlMjZmLTljNDQtNDM0Mi04OTIzLTI2NzYwMzMwYzhhMC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQyMTAxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDAwNzI5N2E4ODU5NWYzY2JmMDdmYWM0NmY5ZTBlNTk5MDVmZDJkOWRhYjBiYWJmNDM5Mzc2MGY0ZGU2MzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YuKNKToeLgM-We-CRfcggKLj_5BaJTX2XbgrV0XwZiM)

Hello, could you post the link again or which driver to install, because I have the same problem and I can't find the solution, thank you.
