### ISSUE TITLE
cannot manually build nerdminer project

### ISSUE THREAD

**Issue by roblatour** [BitMaker-hub/NerdMiner_v2#145]
tried platform io and esp-idf

downloaded the source, it is missing the cmake.txt files.

I tried creating my own, but still got errors.

**Comment by roblatour** [comment]
bump

**Comment by DocBrown101** [comment]
Which of the available does not work?
Have you already tried them all?

![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/11892773/bc5d06f1-ad78-4762-ab1a-26d7c1769a71)

**Comment by BitMaker-hub** [comment]
On platformIO is everything ready to be build, check dev branch if needed

**Comment by roblatour** [comment]
Thank you - I was approaching it wrong.  Its now working for me.
