### ISSUE TITLE
Serial port output errors

### ISSUE THREAD

**Issue by PsySc0rpi0n** [BitMaker-hub/NerdMiner_v2#162]
Hi.
I am using an ESP32 WROOM with no screens attached.
From the serial port output I see these messages:
```
  Receiving: {"id":6,"error":null,"result":true}
  Parsed JSON: Success
  Received message from pool
  Receiving: {"id":7,"error":null,"result":true}
  Parsed JSON: Success
```
Are these "error":null anything relevant or is it just saying that it is null because there were no errors?

**Comment by BitMaker-hub** [comment]
Hi, those are no errors. Stratum protocol is just saying it didn't found any error on shares transmitted.
