### ISSUE TITLE
Password incorrect (fixed)

### ISSUE THREAD

**Issue by Yafsec** [BitMaker-hub/NerdMiner_v2#17]
I had a device that I flashed successfully, but when I tried connecting to the access point it would not connect and show a 'password incorrect' message on my phone. Also the QR did not work. Tried flashing multiple times but the problem persisted. 3 other devices did not have this issue at all.

The solution was to do an "Erase flash" first in the ESP Tool flasher, and then load the firmware again. After that the issue was fixed. Putting it here for others, as a pull request for one line in the readme seemed a bit of overkill. ;)

cheers,
Yafsec

**Comment by BitMaker-hub** [comment]
Ok thanks, I'll add to documentation
