### ISSUE TITLE
Different display types for esp32 devkit

### ISSUE THREAD

**Issue by Prowling123** [BitMaker-hub/NerdMiner_v2#170]
Hello, I am going to try and make use of my spare devkits which I have laying around, but could I get a seperate display for them which would be compatible? Dis someone try this?

**Comment by PsySc0rpi0n** [comment]
I'm using anESP32 WROOM with no screen at all and I only use command line to see what is going on (minicom in Debian)

**Comment by il0vew33d** [comment]
Hello, most of my ESP32 Devkits use a SSD1306 128x64 OLED I2C display. (Wemos Lolin 32 with built-in OLED).
