### ISSUE TITLE
Turn off display

### ISSUE THREAD

**Issue by cprados** [BitMaker-hub/NerdMiner_v2#18]
Instead of having the display always on, it would be nice if there was an option to have it off by default and switch it on for some seconds when a button is pressed.

**Comment by btc-ss** [comment]
This would be nice for sure. The screen warms up a little bit as it stays on. 

I think someone also mentioned a dimming feature would be nice too.

**Comment by BitMaker-hub** [comment]
there is a merge incoming to give a solution to this
