### ISSUE TITLE
move to platform.io

### ISSUE THREAD

**Issue by valerio-vaccaro** [BitMaker-hub/NerdMiner_v2#2]
platform.io will automatically download env and needed libraries, consider to move project on platform.io

**Comment by BitMaker-hub** [comment]
Considered and I'll push an update today

**Comment by PsySc0rpi0n** [comment]
As we are about requests to move te project to other platforms, why not to Gitlab?

**Comment by quinteiroh** [comment]
Let me ask you something: It's too hard to add blockchain information from mempool api on display? Like 15s on the current display and 15s with block height, time, price in USD, etc? It could be double functional: miner and blockchain display api. It's makes sense to you, sir?

The link from mempool api: https://mempool.space/docs/api/rest#get-block-height

Thank you in advance

**Comment by BitMaker-hub** [comment]
[PsySc0rpi0n] Sorry I peronally don't know much Gitlab. But I'll consider on future.

[quinteiroh] Yes, that was in my plan. I'm planning to show Miner stadistics, current pools and block Height. Let me some time hehe. Regarding to mempool, I have another nice idea for a memool DIY project. You will see it next month.

**Comment by quinteiroh** [comment]
Nice! Good to know about it. If you can advance the model of mempool DIY, I would thank you (and I will buy it to don't have to wait...LOL). 

BTW, makes affiliate links from Amazon.es and aliexpress to the products. You can earn some commission with it.

**Comment by BitMaker-hub** [comment]
Moved project to platformIO
