### ISSUE TITLE
Question: Is it possible to connect to lincoin.com mining pool?

### ISSUE THREAD

**Issue by btc-ss** [BitMaker-hub/NerdMiner_v2#20]
@econoalchemist has a pool:

[Taken from recent Spotify pod256 pod cast description]

```
Pick any Lincoin URL:

a)  stratum+tcp://NA.lincoin.com:3333

b)  stratum+tcp://EU.lincoin.com:3333

c) stratum+tcp://LatAm.lincoin.com:3333

d) stratum+tcp://CIS.lincoin.com:3333

e) stratum+tcp://Asia.lincoin.com:3333

f) stratum+tcp://OC.lincoin.com:3333

g) stratum+tcp://Africa.lincoin.com:3333

Then use "pod256.YourAlias" as the worker name.
```

I tried to use 'NA.lincoin.com' and port '3333' but 'shares' counter on NerdMinder does not increase. hash rate stays at 0.00.   

Is any special setup required in order to connect to a mining pool or does the mining pool need to support a specific connection?

**Comment by BitMaker-hub** [comment]
It should not be any problem while they suport stratum protocol.
The only thing could be the connection password, that is currently fixed and in some cases could need to be one specific for a pool
