### ISSUE TITLE
Global Stats display clock/BTC price issue

### ISSUE THREAD

**Issue by backstaia** [BitMaker-hub/NerdMiner_v2#204]
I am using LILYGO T-Display 1.14 and on the Global Stats display clock/BTC price are currently overlapping and making it hard to read. There is enough space, so I assume it should be possible to move the BTC price a few pixel to the left or add additional space between BTC field and clock to avoid the overlapping. Great project btw :-)

**Comment by BitMaker-hub** [comment]
ok, I'll check and move on next release
thx
