### ISSUE TITLE
After firmware upgrade to 1.6.2 (succesful), still 1.6.1 is shown in boot screen

### ISSUE THREAD

**Issue by TheRockaXXX** [BitMaker-hub/NerdMiner_v2#207]
Hi,

I upgraded my NerdMiner (LILYGO T-Display S3) via NM2 flasher online: https://bitmaker-hub.github.io/diyflasher/. The tool says, that the upgrade was successful and the NerdMiner reboots. On the boot screen is still v1.6.1. Is this a bug? How can I check, which version is running?
Thanks

**Comment by BitMaker-hub** [comment]
Hi, Sorry but last update didn't affect the T-Display S3 version. Unfortunatelly even that I missed changing the version on screen. On two weeks I'll push a new update. I'll fix this
