### ISSUE TITLE
Completed setup but not hashing

### ISSUE THREAD

**Issue by joelkuhns** [BitMaker-hub/NerdMiner_v2#21]
I was able to configure the miner but once it went through the setup, the main screen just shows the count for how long the device has been on.  All other items being tracked on the screen are at zero.

**Comment by joelkuhns** [comment]
Cleared the config and tried again, same result.

**Comment by MinerGuy62** [comment]
Mine shows hashing but still not showing up on the pool with 1.4

**Comment by btc-ss** [comment]
@joelkuhns have you tried a different pool just in case?

**Comment by MinerGuy62** [comment]
ckpool and zsolo not registering

**Comment by BitMaker-hub** [comment]
Please, check your firewall settings on your router. 
- Sometimes they block pool connections
- Recheck your wifi config. We will try to add an screen advise when WIFI is not connected properly

**Comment by MinerGuy62** [comment]
I placed the miner into the DMZ and I now see traffic from it.

So even though the pool doesn't show it, is it still solo hashing?

**Comment by joelkuhns** [comment]
I changed it to the pool below and it worked, thanks all!  Probably just blocked on port 3333 or something.  Didn't look into it too far.

btc.zsolo.bid


<br class="Apple-interchange-newline">

**Comment by Lowlirk** [comment]
Hey guys same problem. No hashing. Tried ckpool; zsolo; slushpool... Nerdminer pool showed hash for a few minutes (after leaving nminer on for 20 minutes or so at zero hash) and then dropped to nothing. Placed miner on DMZ - no dice.

**Comment by Lowlirk** [comment]
> Hey guys same problem. No hashing. Tried ckpool; zsolo; slushpool... Nerdminer pool showed hash for a few minutes (after leaving nminer on for 20 minutes or so at zero hash) and then dropped to nothing. Placed miner on DMZ - no dice.

So, this was an issue with my asus router. Turned off "malicious websites" filtering in ai protection.

**Comment by BitMaker-hub** [comment]
Great to know!
