### ISSUE TITLE
[Feature] Switch off the led while screen is off

### ISSUE THREAD

**Issue by julio-matarranz** [BitMaker-hub/NerdMiner_v2#211]
Dear,
Could you implement to switch off the led when we switch off the screen ? (Maybe customisable option from the UI)
Thank you in advance.

**Comment by julio-matarranz** [comment]
I guess the reason is that https://github.com/BitMaker-hub/NerdMiner_v2/blob/Release-1.6.2/src/drivers/displays/dongleDisplayDriver.cpp has empty function body :

```
void dongleDisplay_AlternateScreenState(void)
{
}
```

**Comment by Salaeones** [comment]
hi do you mean the green led on lilygo s3?

**Comment by julio-matarranz** [comment]
> hi do you mean the green led on lilygo s3?

The green one is a power indicator. The commits I finally made were about the RGB led on S3 Dongle
