### ISSUE TITLE
can not display the btc price

### ISSUE THREAD

**Issue by arcsin3x** [BitMaker-hub/NerdMiner_v2#214]
![图片](https://github.com/BitMaker-hub/NerdMiner_v2/assets/76581055/a45e1aa3-79c9-4187-a07f-53b226e9435b)

**Comment by arcsin3x** [comment]
Can you increase the font size of the price？

**Comment by Goohst** [comment]
I can't connect to this API. Can you add the BTC price API to the configuration file and fill it in myself? Can you also write the refresh time of the BTC price into the configuration file so that I can set it myself?

**Comment by StarMikeMichael** [comment]
Yesterday the price resumed showing, and is still showing accurate.  Also, for the first time the the field 32Bits Shares: shows a quantity 3.  

Can any body please tell me what the 32Bits Shares is counting?  Still waiting for my valid blocks to start counting.  But in the mean time, I had ZERO 32 Bit shares for about a week, now that the BTC $0 Price display fixed itself, I show my first THREE 32Bit Shares, and an uptime of two and a half days.  

 (maybe the pool softtwhere was updated, I havn't checked the pool web site yet.)
 I'm still trying to find where in the nerdminer code he gets the price from......  
 
 Totally a fun project!

**Comment by arcsin3x** [comment]
> Yesterday the price resumed showing, and is still showing accurate. Also, for the first time the the field 32Bits Shares: shows a quantity 3.
> 
> Can any body please tell me what the 32Bits Shares is counting? Still waiting for my valid blocks to start counting. But in the mean time, I had ZERO 32 Bit shares for about a week, now that the BTC $0 Price display fixed itself, I show my first THREE 32Bit Shares, and an uptime of two and a half days.
> 
> (maybe the pool softtwhere was updated, I havn't checked the pool web site yet.) I'm still trying to find where in the nerdminer code he gets the price from......
> 
> Totally a fun project!
Hi,where r u from? Some country can not connect api.

**Comment by BitMaker-hub** [comment]
Guys, thanks for your contributions, your changes were merged.
So now everybody will see the price correctly even in China

Regardint 32 bit share means, how many shares were generated by this microminer that has at least 32 bits of zeros on its hash

**Comment by arcsin3x** [comment]
我再提供一种可以连接API，好像无次数限制，     https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD  直接修改API地址为以上地址，然后修改代码 if (doc.containsKey("USD")) bitcoin_price = doc["USD"];      （在src/monitor.h和src/monitor.cpp两个文件中）或者直接使用我的fork

**Comment by arcsin3x** [comment]
> Wait, the one you gave me has limit restrictions? I don't want to be changing it a lot. Changing price every minute is like 1440 request day is this too much????

I'm not sure if there are any restrictions, but the last API address price update took quite some time.This one has a fast update frequency.

**Comment by arcsin3x** [comment]
> Same issue as the above.
> 
> > As of 7/23/25 the Bitcoin price is reading 0. Is there a fix for this. Would be nice to see the price rips on the nerd.

Of couse bro,this API had disable. U need find and replace it. where r u from?
 

1. please use under code replace 
[https://github.com/arcsin3x/NerdMiner_v2/blob/master/src/monitor.cpp](url)  

 `if (doc.containsKey("USD")) bitcoin_price = doc["USD"];`

`if (doc.containsKey("Result")&& doc["Result"].containsKey("corrCode")&&doc["Result"]["corrCode"].containsKey("front")&&doc["Result"]["corrCode"]["front"].containsKey("1")&&doc["Result"]["corrCode"]["front"]["1"].containsKey("price") &&doc["Result"]["corrCode"]["front"]["1"]["price"].containsKey("value") ) bitcoin_price = doc["Result"]["corrCode"]["front"]["1"]["price"]["value"];`

2. please use  `#define getBTCAPI "https://finance.pae.baidu.com/api/getrevforeigndata?query=BTCUSD&finClientType=pc"` 
 replace 
[https://github.com/arcsin3x/NerdMiner_v2/blob/master/src/monitor.h](url) 
`#define getBTCAPI "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD"`

**Comment by arcsin3x** [comment]
> As of 7/23/25 the Bitcoin price is reading 0. Is there a fix for this. Would be nice to see the price rips on the nerd.

Hi,I found the way how to slove this problem.
