### ISSUE TITLE
web.public-pool.io is down

### ISSUE THREAD

**Issue by PSLLSP** [BitMaker-hub/NerdMiner_v2#225]
Not real issue with `NerdMiner` but it is related...

Issue is with the mining pool https://web.public-pool.io/, it is "down" for more than 24 hours. It looks like miners can mine but web interface that shows mining status is not accessible. The pool is protected with CloudFlare shield and that reports that host has **Invalid SSL certificate**, ERROR CODE 526. I see CloudFlare error page and I cannot access the pool, even URL http://web.public-pool.io/ ends at CloudFlare error page...

Because web is not accessible, I cannot find contact information to admins, I cannot read "news", etc. I hope that someone in this community can contact administrators of the pool and ask them to address the issue... I am not sure if they are aware of the certificate issue because miners can mine...

[Error 526](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-526-invalid-ssl-certificate)

**Comment by ryenski** [comment]
Looks like they just need to renew their cert.

**Comment by BitMaker-hub** [comment]
Is up again

**Comment by valshebnik** [comment]
It's again
