### ISSUE TITLE
Support Raspberry PicoW 

### ISSUE THREAD

**Issue by peterwillcn** [BitMaker-hub/NerdMiner_v2#23]
Support Raspberry [PicoW](https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html)

**Comment by chmeulblu** [comment]
To do what ?

**Comment by BitMaker-hub** [comment]
Hi Peter,

I can't add suport to raspberryPicoW because current code is mainly focused on ESP32 devices. You can port it to any ESP32 compatible device and play there
