### ISSUE TITLE
Online flasher version not latest?

### ISSUE THREAD

**Issue by dwightmulcahy** [BitMaker-hub/NerdMiner_v2#235]
Online Flashing (https://nerdminer.satoshistore.io/) showing "NerdMinerv2 1.6.2" but when flashed it shows 1.6.1.

**Comment by drego85** [comment]
Today I used the flasher listed in the Wiki (https://flasher.bitronics.store/) and it installed version 1.6.2.

**Comment by dwightmulcahy** [comment]
Looks like the `setupModeScreen` didn't get updated when 1.6.2 got refactored.

https://github.com/BitMaker-hub/NerdMiner_v2/blob/Release-1.6.1/src/media/images.h
https://github.com/BitMaker-hub/NerdMiner_v2/blob/Release-1.6.2/src/media/images_320_170.h

I believe (from the name) that these are the images that get displayed when it needs to be first config'ed.

**Comment by BitMaker-hub** [comment]
Guys, same code there just a name typo error. This version upgrade was including mainly new boards.
