### ISSUE TITLE
No hash rate update on pool statistic

### ISSUE THREAD

**Issue by mrkaqz** [BitMaker-hub/NerdMiner_v2#24]
Hello,

I just started running nerd miner, it is a great project. 
I have try get BTC address from my trezor and put in a config. firstly i run with ckpool for 2 hours and when I check on the address https://solo.ckpool.org/users/MYBTCADDRESS and it show the page not found then I decided to reset the config and try with  zsolo pool and it was run for 10 hours but still no hash rate show up on the page https://zsolo.bid/en/user/btc?address=MYBTCADDRESS

![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/6989907/58aa5cbe-0335-4a3f-87e7-abc21cfbb0d6)

Not sure this is normal or a bug on the miner.

**Comment by pocket998** [comment]
Hello, 

I have the same problem, No statistic.

Thanks for your answer

**Comment by btc-ss** [comment]
In other threads, it's mentioned that the hash rate is so small it doesn't show up.

**Comment by mrkaqz** [comment]
Thanks for the clerification. let close this issue
