### ISSUE TITLE
NerdMiner is not visible https://web.public-pool.io

### ISSUE THREAD

**Issue by blahos23** [BitMaker-hub/NerdMiner_v2#253]
Hi, after the last update, you can't see the miner in https://web.public-pool.io after entering the BTC address

**Comment by Kalli01** [comment]
I have the same problem. My miner is not visible

**Comment by danielh83** [comment]
I have the same issue. Even after competely new flashing, my three nerdminer are not showing in the public-pool anymore.

**Comment by BitMaker-hub** [comment]
Guys, there was a pool failure past weekend. 
Pool admin is improving things
