### ISSUE TITLE
ESP32-S3-DevKitC-1U - possible to use with provided NerdMiner FW?

### ISSUE THREAD

**Issue by sany3001** [BitMaker-hub/NerdMiner_v2#298]
Hello there!
I would like to run NerdMiner FW on ESP32-S3-DevKitC-1U. I expect that it is possible. 
I have chosen ESP32-WROOM in web flasher. Flashed without problem.
However I do not see NerdMinerAP in the air. ;-(

**Comment by julio-matarranz** [comment]
Dear,
Please check this thread : https://github.com/BitMaker-hub/NerdMiner_v2/discussions/294

**Comment by sany3001** [comment]
Thanks for the reply. Already trying to build locally. Are there any plans to add this device to https://flasher.bitronics.store/ ?

**Comment by sany3001** [comment]
Solved by building FW for `ESP32-S3-devKit1` in PlatformIO. Have to add minimalistic external Wi-Fi antenna to make it working.
Thanks for help @julio-matarranz and thanks for help [RedSalsicha](https://github.com/RedSalsicha)!

**Comment by garunow** [comment]
My friends! which esp32s3 pins should the ili9341 screen be connected to?
