### ISSUE TITLE
Wifi failure

### ISSUE THREAD

**Issue by Wall-8** [BitMaker-hub/NerdMiner_v2#3]
Hi! Cool project!
When I connect to wifi it reboots multiple time and it connects succesfully to the wifi but ends up disconnected and back in AP mode. When I login wifimanager says authentication failure. 

Tried to find solutions in wifimanager github but no real success for a solution, although connection issues seem to be prevalent in wifimanager:
https://github.com/tzapu/WiFiManager/issues/1067

**Comment by BitMaker-hub** [comment]
Hi, this is something difficult to resolve as WiFiManager library is really simple to use but also closed to make changes on it. 
I experimented same behaviour at the begining but this was related to not finding AP, so only when having really bad signal coverage.

Try rebooting wifi credentials (pressing during 5 seconds top right button) and starting again your module. 
Try accessing AP with other phone

If this fails I'll consider to add another way to configure module

**Comment by Wall-8** [comment]
Have rebooted the wifi credentials and accessed with another device. Also stood next to my AP :)
It reboots and loops several time (during the reboot I see connection in the wifi logs and see loaded templates on the screen) but ends up with a an authentication failure.

**Comment by BitMaker-hub** [comment]
Updated new realease that helps with reboots. 
Check if you added your BTC address too
