### ISSUE TITLE
Bad graphics using ESP32-24325028

### ISSUE THREAD

**Issue by fcknzs-love** [BitMaker-hub/NerdMiner_v2#306]
After the first set up flawlessly, I got a second CYD. Unfortunately, with this one I have some display/graphics issues. The colors seem to be inverted, meaning black is white, white is black, yellow is blue and blue is orange. I also believe the image is slightly blurred.

![IMG_20240129_222247433~2](https://github.com/BitMaker-hub/NerdMiner_v2/assets/158100950/0d11e335-7a26-486c-873e-31511cf3d234)
![IMG_20240129_222323079~2](https://github.com/BitMaker-hub/NerdMiner_v2/assets/158100950/83fd0af7-3c2e-44a9-9b2e-b767fa250d9a)
![IMG_20240129_222338370~2](https://github.com/BitMaker-hub/NerdMiner_v2/assets/158100950/83893e83-e2f3-488f-8c9f-9b3b70e5d961)
![IMG_20240129_222351262~3](https://github.com/BitMaker-hub/NerdMiner_v2/assets/158100950/58c940d1-ca96-4502-a872-6099bf0b4dab)

And after all, this one doesn't start mining... CYD is from AliExpress (the cheepest, I could find...). Flashing only worked with https://flasher.bitronics.store . With ESP tool I got an MD5 mismatch..

![IMG_20240129_215623770](https://github.com/BitMaker-hub/NerdMiner_v2/assets/158100950/3bea3c43-03e7-4c0e-8709-9b48cfa89169)
![IMG_20240129_215534954~2](https://github.com/BitMaker-hub/NerdMiner_v2/assets/158100950/ccf95403-a14c-431c-8cc7-4480b67c11d6)

**Comment by paelzer** [comment]
Hello

Regarding the messed up colors...

Seems the firmware on https://flasher.bitronics.store/ is not optimized for the ESP32 2432S028 with two USB connectors. I have that one as well.

Try flashing with Platformio and select "ESP32_2432S028_2USB" as env.

![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/16374477/9386ba5b-e341-4507-9ff4-66031a260599)

Boris

**Comment by UserCripto01** [comment]
Bom dia. Sou novo em programação e tenho o mesmo problema com minha nerminer.
Como faço para atualizar com a Platformio?

**Comment by pedromfa** [comment]
> ESP32_2432S028_2USB

Hello. I have no idea how to work with Platformio.... Is there anyway to have the BIN file for this board and upload the firmware easier for a newbie here? Thank you. :)

**Comment by sany3001** [comment]
It should be pretty easy to work with PlatformIO. Follow this guide:
https://platformio.org/install/ide?install=vscode

Then install Git command line tool. Not sure which one to advice. I am using https://git-scm.com/download/win under Windows.

Clone NerdMiner project
`git clone https://github.com/BitMaker-hub/NerdMiner_v2.git`

Open cloned folder in VScode.

Build with "button" at the bottom of page (choose target first - also on bottom of the page).

**Comment by pedromfa** [comment]
Thank you so much, i think i got it. :)

**Comment by pedromfa** [comment]
Btw, do you kwon how to turn off the screen without turning off the Miner?

**Comment by pedromfa** [comment]
I only have 2 buttons on top. One says RST and the other say BOOT. Tried all possible combos but none just turns off the screen. This is the model with both USB C and micro usb ports.

**Comment by sany3001** [comment]
> > Btw, do you kwon how to turn off the screen without turning off the Miner?
> 
> ![image](https://private-user-images.githubusercontent.com/158797249/307023313-ac284d91-6a07-407d-8c1f-cfb96775d8e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzQ3MTYsIm5iZiI6MTcwODY3NDQxNiwicGF0aCI6Ii8xNTg3OTcyNDkvMzA3MDIzMzEzLWFjMjg0ZDkxLTZhMDctNDA3ZC04YzFmLWNmYjk2Nzc1ZDhlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwNzQ2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODQ2YjY2MmE4NTAzZTg4ZDg0MTU1OWVmYmZkMDVmYTJlN2U0YWU4MDZiMTdhNTFiNTUwMjk0NWU3ODY1OGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JBjh0I8hNbN5FdZ8WoUQ3gSPHwDHKbyVmYpIz3cU6zA)

This guide is not applicable to this specific device.
RST button does reset of the device.

BOOT device works like on one button device:
![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/31476550/5247276e-b373-4534-aa57-c5bfa3da4df5)

(I have tried just single and double click)

More to this: you can somehow press screen to switch screens (if you have touch version).
Not sure how exactly shall this work. It is not very reliable to me.

**Comment by djcasper1975** [comment]
thx i have now got a full colour screen if anybody wants the 2 usb screen ill give you the bins

**Comment by djcasper1975** [comment]
[esp-2432S028_2USB.zip](https://github.com/BitMaker-hub/NerdMiner_v2/files/14855468/esp-2432S028_2USB.zip)
here is the fix i had no idea what im doing but follows 2 reply advice in here to dload software and clone etc and it worked! thankyou heres the final bins. if somebopdy can teach me how to get screen working on the other that would be epic ill do it right away and share it...

**Comment by djcasper1975** [comment]
> > ESP32_2432S028_2USB
> 
> Hello. I have no idea how to work with Platformio.... Is there anyway to have the BIN file for this board and upload the firmware easier for a newbie here? Thank you. :)

@ yes i did what was said and made the files. 
[esp-2432S028_2USB.zip](https://github.com/BitMaker-hub/NerdMiner_v2/files/14855805/esp-2432S028_2USB.zip)

**Comment by fluxres** [comment]
@djcasper1975 Thanks, the files fixed my screen issues.
What is the AP password ?  
MineYourCoins does not work.

**Comment by Russty123** [comment]
What board did you choose when flashing? Mine is a single usb.  I chose the one ending in ‘R’ but screen doesnt work.

**Comment by fluxres** [comment]
I ended up programming through platform IO.  I have the two USB variant and chose that in the build environment.  It worked a treat, have programmed 4 now with no issues.

**Comment by Russty123** [comment]
Yeah im on the platformio. Ive tried the 2 usb build and the and the one ending in ‘r’  mine is just single usb and the board is esp32-2432s028.  When i load the 2usb build colour is pale and the image is off (see pic) and when i load the ‘r’ build screen is small. So which one build was the first one you tried before platformio? 
i might have to start another thread as another issue? 
![IMG_4352](https://github.com/BitMaker-hub/NerdMiner_v2/assets/89437219/13855800-e697-400b-a303-26bfc4743a10)

**Comment by Russty123** [comment]
Screen alignment is good when mining but colours are off. Or is yours still white? Blue and orange like this? I have other miners that look better than this. 

![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/89437219/e0b4d4ba-fd21-4a1e-b8d9-4c867615bb06)

**Comment by fluxres** [comment]
First time I used the "r" variant.  I had the same issues that are shown in your images.  The first time I used the online microminers flash tool as per git.  It's super easy.  Have you tried using that ?  It has worked fine for my "r" variant boards.

**Comment by Russty123** [comment]
Ok i’ll give that a flash tool ago.  If it fails i found this edit of the code that i will try, its inverted colours. Thanks for your time and  help
![IMG_4355](https://github.com/BitMaker-hub/NerdMiner_v2/assets/89437219/f39cc4f3-44f0-4e67-a5b0-349735e52f63)

**Comment by IAmSixNine** [comment]
Thank You. I have the 2 usb one and had off colors. the zip file allowed me to fix this issue. Im not a programmer but trying to learn. So thank you for posting the files I needed.

**Comment by mrijkhals** [comment]
I had this problem with some Arduino oled projects to, nothing to do with nerdminer.
The screens were not RGB but RBG so i had to change the library in order to get it work.
Maybe this fixed the issue over here to.... Anyway the new flash file worked fine thank you

**Comment by BitMaker-hub** [comment]
Hi, this is solved on last version 1.7.0

**Comment by RekOUF** [comment]
@sany3001 can u add esp32-2432s022n support also ? 

more info : 
https://github.com/lsdlsd88/2.2inch_ESP32-2432S022/tree/main/2.2inch_ESP32-2432S022
https://github.com/rzeldent/esp32-smartdisplay-demo/blob/main/platformio.ini

thanks

**Comment by sany3001** [comment]
> @sany3001 can u add esp32-2432s022n support also ?
> 
> more info : https://github.com/lsdlsd88/2.2inch_ESP32-2432S022/tree/main/2.2inch_ESP32-2432S022 https://github.com/rzeldent/esp32-smartdisplay-demo/blob/main/platformio.ini
> 
> thanks

I am sorry, I am not active Nerd Miner developer. And it would cost me now quite a lot of time to doscover how to do that.

I hope that someone else will help.
