### ISSUE TITLE
BTC price API

### ISSUE THREAD

**Issue by 19201003080114** [BitMaker-hub/NerdMiner_v2#310]
BTC price update from api.blockchain.com is too slow. 
Suggest to use https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD

$ symbol for BTC price should be at the front, ie: "$42990" instead of "42990$"

**Comment by BitMaker-hub** [comment]
We changed before this price API regarding some issues on the original price API in some countries. 
The current price value is updated every minute, not much more.

Regarding the $, yes, that make sense I'll modify on new versions

**Comment by 19201003080114** [comment]
Nerdminer to update every minute is OK. 
Issue is that response from api.blockchain.com is updated too slowly. So Nerdminer keeps displaying old prices.
