### ISSUE TITLE
BLACK SCREEN AND NO RESET

### ISSUE THREAD

**Issue by LuanFMelo** [BitMaker-hub/NerdMiner_v2#324]
I configured my nerminer lyligo t display s3 using the tutorial in README and works fine. Today when i was starting up my pc, my nerdminer is simple stucked (i guess) in the boot screen and i cannot reset using the buttons or reinstall the firmaware

**Comment by 19201003080114** [comment]
Press and hold boot button when inserting USB to enter bootloader mode. 
Then use https://espressif.github.io/esptool-js/ to wipe and re-program.

**Comment by LuanFMelo** [comment]
i've tested another cable and works fine.
