### ISSUE TITLE
Support for other ESP32-S3 boards

### ISSUE THREAD

**Issue by mars3142** [BitMaker-hub/NerdMiner_v2#33]
I do own one ESP32-S3 Box and one WT32-SC01 Plus. Both boards are S3 compatible, but do have other display resolutions. It would be nice, to support also other boards for this.

If wanted, I could create PRs for that.

**Comment by deivydaszz** [comment]
Yes, support for any other esp32 board would be awesome

**Comment by dackdel** [comment]
I own two AMOLED https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED and would like support for that

**Comment by StarGateMiner** [comment]
Is the spec of the AMOLED different?

**Comment by GazCore** [comment]
Support ESP32-CH340C-TYPEC 30P?
