### ISSUE TITLE
32BITs Shares

### ISSUE THREAD

**Issue by SinexModelling** [BitMaker-hub/NerdMiner_v2#332]
my own made miner has a 1 32BITs share so what does it means?
![IMG_2242](https://github.com/BitMaker-hub/NerdMiner_v2/assets/159622552/188c5d19-e489-411e-bc0f-85a89ecf3bd2)

**Comment by 19201003080114** [comment]
![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/158797249/e7cd1b49-e4e1-4940-bb9c-3f1fd6c82065)

**Comment by sany3001** [comment]
> 19201003080114

Can you please integrate this picture in README.md here on Github?
