### ISSUE TITLE
Stats don't zero after hard reset

### ISSUE THREAD

**Issue by dwightmulcahy** [BitMaker-hub/NerdMiner_v2#335]
The stats that are saved are not zero'd out when a hard reset is done.  I would expect that they would also be reset.

**Comment by 5Uhe** [comment]
https://github.com/BitMaker-hub/NerdMiner_v2/issues/335#issue-2161942217

**Comment by dwightmulcahy** [comment]
I have a fix; I'm cleaning it up and will push a commit shortly.

**Comment by 5Uhe** [comment]
Yyy

**Comment by 5Uhe** [comment]
Yyyyy
