### ISSUE TITLE
Need some help updating nerdminer v1.6.3 to my Lilygo S3

### ISSUE THREAD

**Issue by GFreedomX** [BitMaker-hub/NerdMiner_v2#336]
I flashed my S3 using both nerdminerv2 flash and the ESP-tool
but my unit is giving me a black screen and when I plug it into my desktop it keep looping ( I think cause I keep hearing the USB device connect and disconnect)

wonder if anyone have this issue?

**Comment by 19201003080114** [comment]
Get to bootloader mode before flashing

**Comment by GFreedomX** [comment]
i am in the bootloader mode when I did the flashing

correct me if I am wrong
I will need to hold done the boot button and power it on to get into the bootloader mode

**Comment by 19201003080114** [comment]
![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/158797249/5fefc0c0-757a-485e-8590-78b0773a8236)

**Comment by GFreedomX** [comment]
![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/48503005/9136db5e-c268-4bfe-b9be-d00db1170d88)
i am able to upload but i am not sure what is the issue with my unit.

is the leaving part normal?

my unit is not able to boot up 
kind of puzzle about this

**Comment by 19201003080114** [comment]
After seeing “Leaving…”, do a power cycle and you will see QR to access WiFi manager.

**Comment by GFreedomX** [comment]
damn let me go try it

**Comment by GFreedomX** [comment]
its working
a typo cause all this issue.
very sorry for the trouble cause
