### ISSUE TITLE
Nicehash ou Binance

### ISSUE THREAD

**Issue by Disuny** [BitMaker-hub/NerdMiner_v2#339]
É possivel conectar-se a rede da Binance ou da Nicehash ?
Estou tento problemas com isso, meu dipositivo simplesmente crash '-'

Sei que não vale a pena, pórem e apenas por aprendizado.

![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/96251111/ae2a58cc-2723-4624-b713-b44d99837139)

**Comment by Disuny** [comment]
Já tentei de todos as formas na URL e sem sucesso
stratum+tcp://sha256.auto.nicehash.com
tcp://sha256.auto.nicehash.com
sha256.auto.nicehash.com

**Comment by BitMaker-hub** [comment]
There are only few compatible pools, those ones are high treshold difficulty, so not working for now
