### ISSUE TITLE
¿ES POSIBLE COLOCAR UNA PANTALLA LED MAS GRANDE?

### ISSUE THREAD

**Issue by NNjess** [BitMaker-hub/NerdMiner_v2#342]
Lo digo para cuestiones más esteticas, no se nada del tema y es una pregunta que se me ocurrió.

**Comment by BitMaker-hub** [comment]
Hola, hay varias pantallas compatibles. Escoge la board que más te interese. Con un poco de maña, también se puede migrar a cualquier otra LCD
