### ISSUE TITLE
Buttons without function

### ISSUE THREAD

**Issue by TGM3D** [BitMaker-hub/NerdMiner_v2#35]
the miner works so far. If USB-C is on the right, the top button is totally reset. It works. I couldn't understand the function of turning the display with a double click and display off. Version 1.4

**Comment by btc-ss** [comment]
I don't believe the screen rotation and display on/off build is released yet.  At least the firmware bins don't appear to be updated yet.

**Comment by FO320** [comment]
I have the same problem and would love to see it fixed!

**Comment by BitMaker-hub** [comment]
Released yet
