### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by dackdel** [BitMaker-hub/NerdMiner_v2#37]
hey how does one flash the firmware, or compile first and then flash the firmware I guess. Is there a blogpost or tutorial beyond "Load the firmware with the binaries from the src/bin folder.
Plug your board and select each file from src/bin with its address"
Cause thats where I am stuck. How do I load the firmware from either the src folder or bin folder. Or from both folders?

**Comment by dackdel** [comment]
Ok found one https://www.youtube.com/watch?v=z5GeXZlM4pU

**Comment by dackdel** [comment]
Ah shit. I have bought the amoled display https://www.lilygo.cc/products/t-display-s3-amoled https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED I guess that is why I cannot see anything on my screen.

**Comment by BitMaker-hub** [comment]
This board uses different screen pins. In future could be supported but not yet

**Comment by dackdel** [comment]
Can you give me a hint of how i might make it work?
