### ISSUE TITLE
Display of Bitcoin-Price is cut off on the last digit / not showing correctly

### ISSUE THREAD

**Issue by csamide** [BitMaker-hub/NerdMiner_v2#377]
I have installed the latest Nerdminer version (1.6.3.) on my esp32-2432s028 board.

Everything works as it should, but on the view with the large price display, the last digit of the price is always cut off and cannot be displayed correctly. (See also screenshot.)

The display is not broken at this point - this area of the screen is always displayed correctly on the other views.
![20240411_235500](https://github.com/BitMaker-hub/NerdMiner_v2/assets/3600618/5ea99c96-e968-47c5-b1b4-9ed55b5515cf)

**Comment by BitMaker-hub** [comment]
This is improved on last 1.7.0 version, can you try?
