### ISSUE TITLE
BCH mining algorithms

### ISSUE THREAD

**Issue by JoKenPo** [BitMaker-hub/NerdMiner_v2#387]
I know that if configured for the BCH pool it works normally, however, I have the impression of having false positives due to the differences between the way each one mines.

Just to be sure, do you believe that for BCH to work it would have to increase the buffer and have some other changes to the ShaTests functions?

**Comment by BitMaker-hub** [comment]
I'm pretty sure it shouldn't, as it's just a fork from Bitcoin it uses the exact same mining algorithm and mining metodology
