### ISSUE TITLE
Error: MD5 of file does not match data in flash!

### ISSUE THREAD

**Issue by vendelin007** [BitMaker-hub/NerdMiner_v2#39]
After flashing starts, first file is flashed properly, next one failed.

Chip is ESP32-S3
Features: Wi-Fi,BLE
Crystal is 40MHz
MAC: 34:85:18:71:80:a8
Uploading stub...
Running stub...
Stub running...
Changing baudrate to 115200
Changed
Not changing the image
Compressed 147588 bytes to 26696...
Writing at 0x0... (50%)
Writing at 0x166d9... (100%)
Wrote 147588 bytes (26696 compressed) at 0x0 in 1.277 seconds.
Hash of data verified.
Leaving...
Compressed 140774 bytes to 25349...
Writing at 0x8000... (50%)
Writing at 0x1e6ed... (100%)
Wrote 140774 bytes (25349 compressed) at 0x8000 in 1.701 seconds.
File  md5: d5991faf1385fa4a96c5f69fc5ea498b
Flash md5: 1cc2316456f823552af84c8a89a96b05
Error: MD5 of file does not match data in flash!

**Comment by BitMaker-hub** [comment]
Check uploading guidelines to enter module on programming state

**Comment by vendelin007** [comment]
I did it exactly as it was written. I put all four files on their respective address. it always fail on the first one :-/

**Comment by vendelin007** [comment]
![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/134617444/7a0ad2d7-c668-47a1-b000-8eaab4520a17)
