### ISSUE TITLE
Error: CryptoJS is not defined

### ISSUE THREAD

**Issue by confettimoney** [BitMaker-hub/NerdMiner_v2#42]
Hello,

When trying to flash the firmware, I am getting the message: "Error: CryptoJS is not defined" and the firmware is not flashed.

Any thoughts on how to solve this?

**Comment by btc-ss** [comment]
Not sure about the error.  Then one I see most often is "device connection lost".

What I usually do I "delete" the firmware from the device a few times then I load the firmware on.

**Comment by confettimoney** [comment]
Solved.
