### ISSUE TITLE
Bin for ESP32-2432S028R seems to be not available in web flasher

### ISSUE THREAD

**Issue by GitHubUser-2024** [BitMaker-hub/NerdMiner_v2#426]
![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/172245105/57c53471-4e94-4e36-bf1f-b0c3aed19d91)

**Comment by julio-matarranz** [comment]
@BitMaker-hub has an PR to accept about this problem. We will let you know when GitHub flash is ok 😉

**Comment by julio-matarranz** [comment]
https://github.com/BitMaker-hub/diyflasher/pull/2

**Comment by julio-matarranz** [comment]
You can try again 😉

**Comment by BitMaker-hub** [comment]
Yes! Give thanks to Julio for this amazing work

**Comment by GitHubUser-2024** [comment]
Perfect, flash was succesful!
