### ISSUE TITLE
M5Stack / M5 Stick ESP32 

### ISSUE THREAD

**Issue by GmrsKissimmee** [BitMaker-hub/NerdMiner_v2#427]
Hello, will the Nerdminer be compatible with the M5Stick from the M5Stack company?

Attached descriptive photo.

https://shop.m5stack.com/products/m5stickc-plus2-esp32-mini-iot-development-kit

![Screenshot 2024-06-10 14 20 10](https://github.com/BitMaker-hub/NerdMiner_v2/assets/155043316/b696c08b-7dc8-4326-87a3-9ef10d57cbd2)

**Comment by BitMaker-hub** [comment]
This board is very similar to other 1,14 boards, try flashing Tdisplay-vt1 or TDongle. 
There is now a prerelease flasher with more boards compatible

https://flasher.bitronics.store/

**Comment by GmrsKissimmee** [comment]
Gracias !!

**Comment by szynwod** [comment]
Hi, have you been able to flash successfully?

**Comment by szynwod** [comment]
Hi, have you been able to flash successfully?

**Comment by GmrsKissimmee** [comment]
Hi, I haven't done the test yet.

**Comment by MarbleCeo** [comment]
i did install on my m5 stick c plus 2 its working well idk how to configure this type of miner but basically get a btc wallet and put on it and thats done the website above bittronics work for the flash and will check what device u have connected
