### ISSUE TITLE
La pool non vede il mio indirizzo address btc

### ISSUE THREAD

**Issue by Totenka** [BitMaker-hub/NerdMiner_v2#43]
Nella configurazione del mio nerd miner ho messo il mio indirizzo btc...ma se cerco tra i minatori il mio indirizzo non esiste

**Comment by Eegee** [comment]
In altri thread, si dice che l'hash rate è così piccolo che non viene visualizzato.

In other threads, it's mentioned that the hash rate is so small it doesn't show up.

**Comment by BitMaker-hub** [comment]
Exactly, miner is not able to reach pool difficulty so you don't see it
