### ISSUE TITLE
Error: MD5 of file does not match data in flash!

### ISSUE THREAD

**Issue by vendelin007** [BitMaker-hub/NerdMiner_v2#44]
![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/134617444/219a3eb0-e639-401a-8d37-83807a657b47)

**Comment by BitMaker-hub** [comment]
This is really strange, should say I don't know why happened. Did you finished the upload?

**Comment by willinilly075** [comment]
Experiencing exactly the same issue.
![ss001](https://github.com/BitMaker-hub/NerdMiner_v2/assets/128996914/e9962da6-eb09-4756-bb49-1f0917ab3c45)

**Comment by willinilly075** [comment]
Any idea what might be causing the hash mismatch?

**Comment by vendelin007** [comment]
> This is really strange, should say I don't know why happened. Did you finished the upload?

Unfortunately upload did not finished yet. I already tried many ways. It always end like this. I'm sad ...

**Comment by BitMaker-hub** [comment]
Please, try the following:
1- Change your cable for a better one
2- Try changing cable orientation, some don't work proper with it
3- Decrease baudrate
4- Change PC
5- Use other webbrowser
6- Use other linux or windows dedicated tools

**Comment by willinilly075** [comment]
Figured this out. It appears Windows Defender was somehow applying file restrictions. Had to right-click every file and remove those. Then it worked out fine.

**Comment by vendelin007** [comment]
> Figured this out. It appears Windows Defender was somehow applying file restrictions. Had to right-click every file and remove those. Then it worked out fine.

Did not work for me :-/

**Comment by vendelin007** [comment]
New flasher fix the issue. Now it's working :) Thanks.
