### ISSUE TITLE
Arduino compilation problem

### ISSUE THREAD

**Issue by lv333ming** [BitMaker-hub/NerdMiner_v2#446]
How to open the NerdSoloMiner project in Arduino, modify and compile it. Hope to get help. I can't see any project files in Arduino IDE, and I don't know what I did wrong.

![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/12588535/197cc8d1-7a7d-4cdf-9b50-f55fc495c5ba)

**Comment by sany3001** [comment]
I have been working with VScode only. Clone, open folder in VScode and build. Really was that simple!
