### ISSUE TITLE
Heltec vision master T190 claim 118kH/s base on esp32 ？？？？

### ISSUE THREAD

**Issue by betterpony** [BitMaker-hub/NerdMiner_v2#459]
I found a board called Heltec vision master T190, and they claim that the hash rate of the ESP32 can reach 118K. I want to know how this is achieved，pool accept it's work ，
![image](https://github.com/user-attachments/assets/6f93705e-09d9-47ff-a780-8b2cf0a1fe9d)

Is there still untapped potential in the ESP32? I find their [github](https://github.com/NMminer1024/NMMiner) and [purchase link](https://www.aliexpress.com/item/1005007449552504.html)，but they only push a firmware file on github and really cheap，all of this looks real.

**Comment by BitMaker-hub** [comment]
Hi! wow, I've just got surprised, hehe. 
Something to consider, really hehe

Unfortunatelly they didn't opensource the firmware, even copied almost everything

**Comment by betterpony** [comment]
I was also very shocked when I first saw it. I suspect that this hash rate is fabricated.

**Comment by BitMaker-hub** [comment]
I don't really know, I'm very curious. In fact they says exprimed sha256d into the limits inside the processor. This also was done  using  almost assembler.
I know there are more things to do, but don't know if they do it

**Comment by JohnTaipei** [comment]
esp32-s3 + st7789 1.9"

**Comment by JohnTaipei** [comment]
I am trying NMMiner V0.2.10

**Comment by JohnTaipei** [comment]
it works
113KH/s
https://youtu.be/zlHMf11gVq8?si=BVC3KG2avags0nD7

**Comment by HarukiToreda** [comment]
It works, I have it also using the Heltec V3 with it too at 119kh/s
![20240908_023214](https://github.com/user-attachments/assets/98917711-0266-447a-9632-8de84efb8113)
![20240908_023208](https://github.com/user-attachments/assets/201656c2-72d9-4062-aea1-9471bf89153b)

**Comment by HarukiToreda** [comment]
I got the firmware here
https://github.com/NMminer1024/NMMiner

**Comment by BitMaker-hub** [comment]
YEs, this works but is not opensource. They just copied firmware improved it but just keeped it as a license scheme.
No more to say
