### ISSUE TITLE
Cannot set BTC address

### ISSUE THREAD

**Issue by kerner1000** [BitMaker-hub/NerdMiner_v2#48]
I do not see a possibility to configure the BTC address after a reset.

<img width="626" alt="Screenshot 2023-05-31 at 11 54 15" src="https://github.com/BitMaker-hub/NerdMiner_v2/assets/13817521/bf449d89-6ba2-4383-9e47-aee47f971a76">

**Comment by BitMaker-hub** [comment]
Hi! 
If you have any trouble from your mobile phone, you can try from any PC 💻. Connect to nerdminerAP and  navigate to 192.168.4.1
