### ISSUE TITLE
Zero Hash Rate

### ISSUE THREAD

**Issue by SatoshyBoy** [BitMaker-hub/NerdMiner_v2#54]
After running for a few hours, the hash rate goes to zero.  That issues usually takes 24 hours to happen.

**Comment by ahop117** [comment]
This also happens in my case. Usually ~24h, then 0 hash rate, and have to disconnect cable and connect again to reboot. Maybe is a problem with ckpool? Don't know if with other pools this happens.

**Comment by singerscreations** [comment]
ckpool is the least problematic. With other pools, it happens more often and reboots are not uncommon either. Lots of bugs in the current version.

**Comment by btc-ss** [comment]
Ckpool ran for 340+ hours before I hit the zero hash rate.  Then reboot and it is fine again.
