### ISSUE TITLE
Error during flashing ESP32S3 

### ISSUE THREAD

**Issue by piwii** [BitMaker-hub/NerdMiner_v2#59]
Hello !

Thank you for this amanzing little miner and all your work.

I have a problem : when I load the firmware with the binaries from the src/bin folder, i have the following error :

![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/3097527/0e040c3f-e80b-4eb6-9288-2aef1ab0ee57)

This is weird because the miner seems to work perfectly.

How can I verify if there are something wrong ?

**Comment by alcar21** [comment]
> 1. Download and install [Visual Studio Code (VSCode)](https://code.visualstudio.com/)
> 2. Install VSCode Extension [PlatformIO IDE](https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide) and restart VSCode
> 3. Clone NerdMiner Repository: `git clone https://github.com/BitMaker-hub/NerdMiner_v2.git`
> 4. Connect your ESP32 device via USB
> 5. Open PlatformIO Tool Window and pick the cloned / existing PlatformIO-based project (NerdMiner v2)
> 6. Open PlatformIO Tool Window and execute following steps:
> 
> * `Clean` to remove the pre-built binary files (placed in `bin`)
> * `Build` to build the binary files (placed in `bin`)
> * `Upload` to flash the self-built binary files to ESP32 device
> 
> 7. Connect to NerdMiner AP (Access Point), see Credentials in [NerdMiner Configuration](https://github.com/BitMaker-hub/NerdMiner_v2#nerdminer-configuration)
> 8. Open `192.168.4.1` in your system browser
> 9. Open WiFi Manager
> 10. Enter your own WiFi credentials (SSID and Password)
> 11. Configure Solo Mining Pool (personal recommendation: `btc.zsolo.bid` with port `6056` due to "Very Low Difficulty")
> 12. Enter your Bitcoin wallet address in case you win the mining lottery (see [SoloChance](https://solochance.com/))
> 13. Save your settings and wait for restart
> 
> Enjoy and good luck!

@BitMaker-hub, it's good information to add to the README.
