### ISSUE TITLE
What is "normal" in time or amount of 16bit shares to get a 32bit share?

### ISSUE THREAD

**Issue by PMK** [BitMaker-hub/NerdMiner_v2#62]
After 12 hours I have many 16bit shares, but still 0 32bit shares. What is likely normal to get a 32bit share of the amount of 16bit shares, or in time?
I get a feeling that the issue about parsing JSON, mentioned [here](https://github.com/BitMaker-hub/NerdMiner_v2/issues/50#issuecomment-1585762114), could be a problem why it doesn't get 32bit shares? Or am I wrong?

**Comment by StarGateMiner** [comment]
> After 12 hours I have many 16bit shares, but still 0 32bit shares. What is likely normal to get a 32bit share of the amount of 16bit shares, or in time? I get a feeling that the issue about parsing JSON, mentioned [here](https://github.com/BitMaker-hub/NerdMiner_v2/issues/50#issuecomment-1585762114), could be a problem why it doesn't get 32bit shares? Or am I wrong?

My miner ran 137h and only found 2 32bit shares with over 151k 16bit shares.
It then dropped out and had to reset.

I need todo some more trial and error checks with the pools, my worry is also as yours, I know small device but want to make sure its functioning 100percent.

**Comment by santitf** [comment]
My 3 devices did go to zero 9 hours ago (zsolo and port very low hash). I tried to reset or reboot my router with no luck. Change to ckpool fix the problem. 
I will test today zsolo pool.

**Comment by golden-guy** [comment]
In the current code, this "Parsed JSON: unknown" is always returned as default, when no expected pattern is matching. No need to worry in that case, it's just a plain ACK response from the pool.

I should be getting my device today, then I will do a testnet setup first. Unless this has been already done and miner verified on testnet? Didn't see a note about that yet, though.

**Comment by nickfromthebus** [comment]
after 3.5 hour my first 32bit share doesnt seem so bad lol
