### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by Wenze** [BitMaker-hub/NerdMiner_v2#64]
Using firmware '0x10000_firmware.bin', the only button option that works for me is:
_Hold 5 seconds > top right button to reset the configurations and reboot your NerdMiner._

Device: LilyGO TTGO T-Display-S3 ESP32-S3 - met 1.9 inch TFT Display

TOP BUTTON
- ~~One click > change screen.~~
- Hold 5 seconds > top right button to reset the configurations and reboot your NerdMiner.
- ~~Hold and power up > enter configuration mode and edit current config via Wifi. You could change your settings or verify them.~~

BOTTOM BUTTON

- ~~One Click > turn the screen off and on again~~
- ~~Double click > change orientation (default is USB-C to the right)~~

**Comment by ElChopChop** [comment]
Hi @PMK the instructions you're looking at refer to the v1.5.1 firmware. 

The instructions for the firmware you're running are shown below.

With the USB-C port to the right:
- The **top** button allows you to reset the configurations and reboot your NerdMiner. Just hold it for 5 seconds.
- Click the **bottom** button once to turn the screen off and on again
- **Double click** to change the orientation (default is USB-C to the right)
