### ISSUE TITLE
Global Stats screen says "halving" when it should say "difficulty" or similar

### ISSUE THREAD

**Issue by ElChopChop** [BitMaker-hub/NerdMiner_v2#65]
On the Global Stats screen there's a section which says "halving". I believe this metric actually refers to the blocks until the next difficulty adjustment.

**Comment by golden-guy** [comment]
True, this metric shows the remaining blocks count for the current epoch.

**Comment by BitMaker-hub** [comment]
True, I got this after the update. I'll modify it correctly.

**Comment by ElChopChop** [comment]
This has now been changed to reflect the number of blocks to the next halving.
