### ISSUE TITLE
Crash/restart on Global Stats screen

### ISSUE THREAD

**Issue by sk3pt1k** [BitMaker-hub/NerdMiner_v2#69]
The miner works without issue on the main and Clock Miner screens, but when on the Global Stats screen the device crashes and restarts within 5-30 minutes.

**Comment by santitf** [comment]
Mine crash int same time, at global stats

**Comment by BitMaker-hub** [comment]
Hi, I've seen it too. I'll check why happens and bring a new update.

**Comment by sk3pt1k** [comment]
Any updates on this? Still happening on latest release

**Comment by sk3pt1k** [comment]
FYI this seems to no longer be happening on the current state of `main`

**Comment by BitMaker-hub** [comment]
Yes, I can confirm.

**Comment by sk3pt1k** [comment]
Nope, I jinxed it, it's happening right now
