### ISSUE TITLE
battery ?

### ISSUE THREAD

**Issue by chmeulblu** [BitMaker-hub/NerdMiner_v2#7]
hi,
since the ESP allows it. i plugged a battery on it. 
![IMG20230425141618](https://user-images.githubusercontent.com/93862688/235428407-a07f0b49-9bf6-4eaa-965a-9f7d31754c2d.jpg)
i used one like the one on the photo on  another ESP for another project ( the very good PoS ).

the idea is sometimes, for show or demo purposes  or for fun on a desk to have the miner working without any wire. looks nicer and .. mysterious !
not for a long time but an hour or 2 would be nice.

the ESP is 3,7v so it could work on the 3.4v ... and it .. almot does.
when unplugged with the battery in it  it goes on mining allright i think. but the screen stays black. you recover it when plugging again and see that the process is still on and running. ( looks like it anyway)

so it is close. 
what is it missing ? some mA ?  or is there a hardware safety measure ? 
Could some code arrange that ? :  test if battery on and make it work at a "slower" hashrate for example ? 
or add a little electronic ? ( i saw an addon with a resistor to be able to tune the vent speed...)

It looks to me like a nice possible upgrade
i go from afar  but i am quite willing to help work on it if you and/or other people think it is interesting.

but you haven't proposed or spoken about it, i suppose there is a good reason for that...

this is more a proposal with an issue than a real issue though. let me know if this should be posted elsewhere 

Chmeulblu

**Comment by BitMaker-hub** [comment]
Hi Chmeublu

I'll set this issue closed as yesterday I made an update related to a know bug on lilygo tDisplay related to 5V and battery. This let's you work with battery

I'll release a new version today that let you work with battery

**Comment by chmeulblu** [comment]
hi,
it does work. nice ! great job. i am impressed by the miner. 

the battery can easily be glued inside the top cover. and it works nicely. it also gives the miner some weight : it feels like its mining harder :-)
it may not be good to  have it working all the time ( for the battery also that is drained each time) and more usefull to be able to start it when you want ( demos , academic purposes, fun with friends...) . 
The next step would be to modify the 3D case to allow for adding a small and inexpensive on/off standard electronic switch. no programming there. i could try that whithout any disruption to the project . just a nice addon for those who want to add this feature.
example of switch :
![common electronic switches](https://github.com/BitMaker-hub/NerdMiner_v2/assets/93862688/2dc39495-e64c-4c9a-b3a5-a02236553ccf)
i ve seen it done for exactly that purpose on ben arc bitcoin point of sale .  Pictures down bellow are an example of modification on the 3D base box ( not the cover). doesn't look that difficult, need no screw or anything. it could be added on the main case,just under the cover , on the plug side. 
![example 3D add on for switch](https://github.com/BitMaker-hub/NerdMiner_v2/assets/93862688/013a5930-7c35-4b92-90a7-3ff915e61345)
![example 3D add on for switch -2](https://github.com/BitMaker-hub/NerdMiner_v2/assets/93862688/733254c0-eb84-49fe-a8f8-a80f73cd4e80)
![example 3D add on for switch -3](https://github.com/BitMaker-hub/NerdMiner_v2/assets/93862688/e0c15d86-6880-4493-a4e5-0c8be859eae5)
i am no fusion 360 or cad expert but i could try to work on it as a contribution to your project. if you are interested. if so can you send me the source 3D files to try that ? 
let me know.
