### ISSUE TITLE
Default screen and orientation

### ISSUE THREAD

**Issue by sk3pt1k** [BitMaker-hub/NerdMiner_v2#71]
Would be nice to configure the default screen and orientation on power-up

**Comment by OodavidsinoO** [comment]
![image](https://github.com/BitMaker-hub/NerdMiner_v2/assets/29495931/b6614360-d413-4348-a0f3-2acf63471b54)
Change 1 to 3 if you want to alter the default screen orientation.

**Comment by sk3pt1k** [comment]
> I'll add this to wificonfig, right?

Perfect!

**Comment by izhzz** [comment]
Would it be possible to change the background graphics? If yes, where should I look at in the build?  Thanks!
