### ISSUE TITLE
Expected avg hashrate

### ISSUE THREAD

**Issue by golden-guy** [BitMaker-hub/NerdMiner_v2#76]
Hello,
just wondering what's the expected avg hashrate? With the very same hardware, I have seen YT videos with the hash rate ranging from 20-21 to 21-22 KH/s, but also up to 27. Running mine at about 22KH/s on the latest 1.5.1beta build.

**Comment by sk3pt1k** [comment]
Yeah, just shy of 22KH/s on average for me on latest build

**Comment by BitMaker-hub** [comment]
Exactly, latest firmware has an average of 22kH/s
