### ISSUE TITLE
Inestabilidad en los KH/s

### ISSUE THREAD

**Issue by westsobe** [BitMaker-hub/NerdMiner_v2#78]
Hola @BitMaker-hub !

¿Es normal que la tasa de KH/s no sea estable? 

Me explico:

Cada 20-30 segundos la tasa se va a 0, aunque se recupera enseguida y vuelve a los 21 - 22 KH/s. El bucle se repite constantemente.

Tengo instalada la última versión beta y apuntando al pool solo.ckpool.org 

Muchas gracias por tu trabajo!!

**Comment by santitf** [comment]
Hola! Tienes conectado el cable usb al PC o directamente a una base de carga?

**Comment by westsobe** [comment]
Lo tengo conectado directamente a un puerto USB del router, y anteriormente al PC para flashearlo. 
La verdad que a una base de carga directa no lo he conectado. 
Pruebo y posteo con el resultado ;)
Gracias!

**Comment by westsobe** [comment]
Efectivamente, ese era el problema. Conectado a una base de carga es completamente estable. 
Muchas gracias por el soporte crack!!
Un saludo!!

**Comment by santitf** [comment]
> Efectivamente, ese era el problema. Conectado a una base de carga es completamente estable. 
> 
> Muchas gracias por el soporte crack!!
> 
> Un saludo!!

Eso mismo he experimentado pero no le encuentro una explicación. Directamente en un router no lo he probado pero cada vez que lo dejo conectado al pc, va fluctuando tal y como has comentado. Suele estabilizarse al apagar el pc si el puerto usb puede alimentar el esp32.
