### ISSUE TITLE
LILYGO T-Display 1.14

### ISSUE THREAD

**Issue by rhcpdu13** [BitMaker-hub/NerdMiner_v2#81]
Hi !
I'm trying to test NerdMiner on my LILYGO® TTGO T-Display 1.14 https://fr.aliexpress.com/item/33048962331.html?gatewayAdapt=Msite2Pc

But the screen is black. The flash is done with the tool flash_download_tool_3.9.3
My first question is : It is compatible ? if yes, how i can do it ?

Thank you !!

**Comment by ymongo** [comment]
same here, https://bitmaker-hub.github.io/diyflasher/ says Successfully flashed NerdMinerv2 Latest Version T-DisplayS3

but screen is black, and no WIFI AP

**Comment by WantClue** [comment]
> Hi ! I'm trying to test NerdMiner on my LILYGO® TTGO T-Display 1.14 https://fr.aliexpress.com/item/33048962331.html?gatewayAdapt=Msite2Pc
> 
> But the screen is black. The flash is done with the tool flash_download_tool_3.9.3 My first question is : It is compatible ? if yes, how i can do it ?
> 
> Thank you !!

You can install this piece of software on almost every esp32, you can achieve this by using the esp32-devkit PlatformIO tasks.

**Comment by ymongo** [comment]
> PlatformIO tasks

do you have any step by step on how to PlatformIO? In any case I'm investigating it now, looks exciting!

**Comment by ymongo** [comment]
so far: 
- esp32-devkit PlatformIO task on VSCode gives me missing FREETROS.h file...
- TTGO Display task gives me missing sdk file....

**Comment by AbsoluteDEF** [comment]
Yeah mine too, but do we need different firmwares for different chips?

**Comment by BitMaker-hub** [comment]
We are adding support on this, there is still some incompatibility with libraries I'm holding

**Comment by ZycoMonk** [comment]
i have the same problem... 
Chip is ESP32-D0WDQ6 (revision 1)
Crystal is 40MHz

**Comment by BitMaker-hub** [comment]
This week started with ESP32devkit support, soon will give TDisplay 1.14 to

**Comment by ymongo** [comment]
Working fine here on TDisplay 1.14 , I think issue can be closed!

**Comment by BitMaker-hub** [comment]
Thanks! Issue closed

**Comment by Bibit2669** [comment]
hello, for me it is impossible to detect T-Display 1.14 on the ESPtool. nor even on the .io, how to make it visible to install the .bin?
