### ISSUE TITLE
Suggestion for S3 AMOLED

### ISSUE THREAD

**Issue by dackdel** [BitMaker-hub/NerdMiner_v2#82]
https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED/issues/4#issuecomment-1619193784 

Please check out this comment. Can someone with more experience than me help try out this suggestion?

**Comment by bernaction** [comment]
Any ETA?

**Comment by marcosgabbardo** [comment]
+1 nerdminer does not work with AMOLED

**Comment by dackdel** [comment]
> Any ETA?

No. Fix it yourself I guess? Did you try the instructions in the link. If you did, did it work? If not then just wait a year or two.

**Comment by BitMaker-hub** [comment]
Guys this issue was closed because release 1.6.2 works with amoled
