### ISSUE TITLE
Issue Programing ESP32 S3

### ISSUE THREAD

**Issue by TrustinDo** [BitMaker-hub/NerdMiner_v2#83]
I was trying to program my lilygo esp32 when i got done putting the file in and pressing program the esp tool said leaving..
i could use help asap
![Copy of Screenshot (1)](https://github.com/BitMaker-hub/NerdMiner_v2/assets/138975766/745e29d4-0c6e-419d-9c2e-1dc53c4a135a)

**Comment by 21orangehat** [comment]
Hey @TrustinDo ,

I was having the same problem.

I saw that this online platform is having issues with NerdMiner_v2 and the guys moved the flashing step to Platform.IO

They still need to update the REAMD.me but you can follow this[1] video.
[1]https://www.youtube.com/watch?v=cI0fCBFyQok

Best

**Comment by BitMaker-hub** [comment]
Hi I added a new flasher utility to github expressed as https://bitmaker-hub.github.io/diyflasher/
