### ISSUE TITLE
Miner not loading block templates

### ISSUE THREAD

**Issue by MichaelAntonFischer** [BitMaker-hub/NerdMiner_v2#89]
I have one stubborn miner that just doesn't want to load any block templates. I flashed it several times, tried various wifis, tried all the pools, this beast just doesn't want to mine. Any idea how to trouble shoot? At this point I think it must be a hardware issue...

**Comment by Hellangel1987** [comment]
mine stoped working too

**Comment by sany3001** [comment]
How was this solved?
I had understood that BTC address needs to be provided to start mining (documentation was updated with this info already).
But if the above guy says, it stopped working, it won't be the case.
