### ISSUE TITLE
Brightness Adjustment

### ISSUE THREAD

**Issue by dadofsambonzuki** [BitMaker-hub/NerdMiner_v2#91]
1. It would be great to be able to adjust brightness via the config page.
2. Bonus points to enable this to be done on a time schedule, e.g. to dim at night if used for a bedside clock. 👀

**Comment by santitf** [comment]
Great idea!

**Comment by alcar21** [comment]
We have already implemented it. In the next version, @BitMaker-hub will merge this code.
