### ISSUE TITLE
ESP32-2432S028

### ISSUE THREAD

**Issue by jeansanches97** [BitMaker-hub/NerdMiner_v2#94]
What modifications would I need to do to run the nerdminer in a low cost ESP32-2432S028? I can flashing but it does not boot and does not display image.

- ESP-WROOM-32
- Clock:  240mhz
- SRAM: 520kb
-  5VCC
- Wi-fi 802.11b/g/n/e/i
- Bluetooth 4.2
- UART, SPI, i2C, PWM

https://aliexpress.com/item/1005004962072262.html

**Comment by marssystems** [comment]
Take a look at this project -

https://github.com/BitMaker-hub/ESP32_NerdMiner/tree/master

should work for you.

**Comment by BitMaker-hub** [comment]
Added on 1.6.2
