### ISSUE TITLE
how much NerdMiner v2 in one network?

### ISSUE THREAD

**Issue by blahos23** [BitMaker-hub/NerdMiner_v2#96]
hi, how many can i connect h NerdMiner v2 in one network?
And when I apply via this link NM2 online: https://bitmaker-hub.github.io/diyflasher/ my original wifi settings and BTC addresses are deleted

**Comment by golden-guy** [comment]
You can use as many nerdminers as your network can support. In regards to flashing, the settings should be kept unless you fully erase the flash during the flash process.
