### ISSUE TITLE
Nerdminer submits invalid shares (below 1e-9)

### ISSUE THREAD

**Issue by benjamin-wilson** [BitMaker-hub/NerdMiner_v2#97]
My ultra-low diff compatible pool (https://github.com/benjamin-wilson/public-pool) receives invalid shares nerdminers. All other miners tested submit valid shares. Either the header construction or the double sha hashing algorithm appears to be incorrect.

**Comment by streamofstars** [comment]
> does not receive valid shares from nerdminers

See https://github.com/BitMaker-hub/NerdMiner_v2/issues/32#issuecomment-1556031121

**Comment by benjamin-wilson** [comment]
I should've clarified that it does receive shares but they are below the specified 1e-9 difficulty.
https://github.com/BitMaker-hub/NerdMiner_v2/blob/3ab4a2fb058bbecefa274bd936490ade72a384db/src/mining.cpp#L301C20-L301C20

**Comment by golden-guy** [comment]
Should be all fixed now with https://github.com/BitMaker-hub/NerdMiner_v2/pull/100

Thanks for the test sessions to sort out all these issues!

**Comment by BitMaker-hub** [comment]
This was solved on 1.6.0
